version: '3.8'

services:
  backend:
    image: squwsun/author_api_node:latest
    container_name: backend-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - /home/squwsun/Documents/api_learn/nodejs_express:/app  # Mount the backend code directory

  frontend:
    image: squwsun/author_front_end:latest
    container_name: frontend-container
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - /home/squwsun/Documents/angular_learn/authors-project:/app  # Mount the frontend code directory

networks:
  app-network:
    driver: bridge
