services:
  backend:
    build:
      context: /home/squw/authors-project-api-nodejs-express
      dockerfile: Dockerfile
    image: squwsun/author_api_node:latest
    container_name: backend-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    build:
      context: /home/squw/authors-project
      dockerfile: Dockerfile
    image: squwsun/author_front_end:latest
    container_name: frontend-container
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
